apiVersion: v1 
kind: Pod 
metadata: 
  name: enviroment
spec: 
  containers:
  - name: nginx
    image: nginx
    env:
      - name: course
        value: EKS 
      - name: clustername
        value: expense